<?php

namespace Container09lkh9p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllercompanyHomeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XOSE210.App\Controller\HomeController::companyHome()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XOSE210.App\\Controller\\HomeController::companyHome()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'developerRepo' => ['privates', 'App\\Repository\\DeveloperProfileRepository', 'getDeveloperProfileRepositoryService', true],
        ], [
            'developerRepo' => 'App\\Repository\\DeveloperProfileRepository',
        ]))->withContext('App\\Controller\\HomeController::companyHome()', $container);
    }
}
