<?php

namespace ContainerT8DvPPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BjnIB1PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BjnIB1P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BjnIB1P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\CompanyController::register()', 'getCompanyControllerregisterService', true],
            'App\\Controller\\CompanyController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\CompanyController::login()', 'getCompanyControllerloginService', true],
            'App\\Controller\\DevController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\DevController::register()', 'getDevControllerregisterService', true],
            'App\\Controller\\DevController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\DevController::login()', 'getDevControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\CompanyController::register()', 'getCompanyControllerregisterService', true],
            'App\\Controller\\CompanyController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\CompanyController::login()', 'getCompanyControllerloginService', true],
            'App\\Controller\\DevController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\DevController::register()', 'getDevControllerregisterService', true],
            'App\\Controller\\DevController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\DevController::login()', 'getDevControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CompanyController::register' => '?',
            'App\\Controller\\CompanyController::login' => '?',
            'App\\Controller\\DevController::register' => '?',
            'App\\Controller\\DevController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CompanyController:register' => '?',
            'App\\Controller\\CompanyController:login' => '?',
            'App\\Controller\\DevController:register' => '?',
            'App\\Controller\\DevController:login' => '?',
        ]);
    }
}
