<?php

namespace ContainerYx093Ov;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerdeveloperHomeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I5nia.Y.App\Controller\HomeController::developerHome()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I5nia.Y.App\\Controller\\HomeController::developerHome()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jobPostRepo' => ['privates', 'App\\Repository\\JobPostRepository', 'getJobPostRepositoryService', true],
        ], [
            'jobPostRepo' => 'App\\Repository\\JobPostRepository',
        ]))->withContext('App\\Controller\\HomeController::developerHome()', $container);
    }
}
