<?php

namespace ContainerVYoRFD7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RIVawP7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RIVawP7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RIVawP7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\CompanyController::register()', 'getCompanyControllerregisterService', true],
            'App\\Controller\\CompanyController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\CompanyController::login()', 'getCompanyControllerloginService', true],
            'App\\Controller\\DevController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\DevController::register()', 'getDevControllerregisterService', true],
            'App\\Controller\\DevController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\DevController::login()', 'getDevControllerloginService', true],
            'App\\Controller\\HomeController::companyHome' => ['privates', '.service_locator.XOSE210.App\\Controller\\HomeController::companyHome()', 'getHomeControllercompanyHomeService', true],
            'App\\Controller\\HomeController::developerHome' => ['privates', '.service_locator.I5nia.Y.App\\Controller\\HomeController::developerHome()', 'getHomeControllerdeveloperHomeService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\CompanyController::register()', 'getCompanyControllerregisterService', true],
            'App\\Controller\\CompanyController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\CompanyController::login()', 'getCompanyControllerloginService', true],
            'App\\Controller\\DevController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\DevController::register()', 'getDevControllerregisterService', true],
            'App\\Controller\\DevController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\DevController::login()', 'getDevControllerloginService', true],
            'App\\Controller\\HomeController:companyHome' => ['privates', '.service_locator.XOSE210.App\\Controller\\HomeController::companyHome()', 'getHomeControllercompanyHomeService', true],
            'App\\Controller\\HomeController:developerHome' => ['privates', '.service_locator.I5nia.Y.App\\Controller\\HomeController::developerHome()', 'getHomeControllerdeveloperHomeService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CompanyController::register' => '?',
            'App\\Controller\\CompanyController::login' => '?',
            'App\\Controller\\DevController::register' => '?',
            'App\\Controller\\DevController::login' => '?',
            'App\\Controller\\HomeController::companyHome' => '?',
            'App\\Controller\\HomeController::developerHome' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CompanyController:register' => '?',
            'App\\Controller\\CompanyController:login' => '?',
            'App\\Controller\\DevController:register' => '?',
            'App\\Controller\\DevController:login' => '?',
            'App\\Controller\\HomeController:companyHome' => '?',
            'App\\Controller\\HomeController:developerHome' => '?',
        ]);
    }
}
