<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT8DvPPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT8DvPPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT8DvPPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT8DvPPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT8DvPPx\App_KernelDevDebugContainer([
    'container.build_hash' => 'T8DvPPx',
    'container.build_id' => 'eb8ce8cf',
    'container.build_time' => 1735929847,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT8DvPPx');
