<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container09lkh9p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container09lkh9p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container09lkh9p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container09lkh9p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container09lkh9p\App_KernelDevDebugContainer([
    'container.build_hash' => '09lkh9p',
    'container.build_id' => '6358a821',
    'container.build_time' => 1735999879,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container09lkh9p');
