<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_company_register' => [[], ['_controller' => 'App\\Controller\\CompanyController::register'], [], [['text', '/company/register']], [], [], []],
    'app_company_login' => [[], ['_controller' => 'App\\Controller\\CompanyController::login'], [], [['text', '/company/login']], [], [], []],
    'app_dev_register' => [[], ['_controller' => 'App\\Controller\\DevController::register'], [], [['text', '/dev/register']], [], [], []],
    'app_dev_login' => [[], ['_controller' => 'App\\Controller\\DevController::login'], [], [['text', '/dev/login']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\CompanyController::register' => [[], ['_controller' => 'App\\Controller\\CompanyController::register'], [], [['text', '/company/register']], [], [], []],
    'App\Controller\CompanyController::login' => [[], ['_controller' => 'App\\Controller\\CompanyController::login'], [], [['text', '/company/login']], [], [], []],
    'App\Controller\DevController::register' => [[], ['_controller' => 'App\\Controller\\DevController::register'], [], [['text', '/dev/register']], [], [], []],
    'App\Controller\DevController::login' => [[], ['_controller' => 'App\\Controller\\DevController::login'], [], [['text', '/dev/login']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
];
